included: # paths to include during linting. `--path` is ignored if present.
  - Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules:
  - identifier_name
line_length: 120