before_install:
  - bundle install
install:
  - ./decrypt.sh
  - bundle exec pod install --repo-update
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace TCC.xcworkspace -scheme TCC CODE_SIGNING_REQUIRED=NO

language: objective-c
osx_image: xcode9.3
xcode_project: TCC.xcworkspace
xcode_scheme: TCC
xcode_sdk: iphonesimulator9.3

notifications:
  email: false