before_install:
  - bundle install
install:
  - ./scripts/decrypt.sh
  - bundle exec pod install --repo-update
script:
    - xcodebuild clean build -sdk iphonesimulator11.4 -workspace TCC.xcworkspace -scheme TCC CODE_SIGNING_REQUIRED=NO

language: objective-c
cache:
  - bundler
  - cocoapods
osx_image: xcode9.4
xcode_project: TCC.xcworkspace
xcode_scheme: TCC
xcode_sdk: iphonesimulator11.4

notifications:
  email: false