language: objective-c
cache:
  - cocoapods

before_install:
  - gem install cocoapods
  - bundle install
install:
  - bundle exec rake
  - bundle exec pod install --repo-update
script:
  - xcodebuild clean build -sdk iphonesimulator12.0 -workspace TCC.xcworkspace -scheme TCC CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

osx_image: xcode10
xcode_project: TCC.xcworkspace
xcode_scheme: TCC
xcode_sdk: iphonesimulator12.0

notifications:
  email: false